title: Çağlar Personal Website
email: cag952kap@gmail.com
description: Cybersecurity, mechatronics and algorithm solutions blog.
baseurl: ""
url: "https://caglarbey.github.io"
theme: minima
plugins:
  - jekyll-feed
